# Generated by Django 5.2.10 on 2026-02-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busop', '0002_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='busop_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('OTP', models.CharField(max_length=6)),
            ],
        ),
    ]
