# Generated by Django 5.2.10 on 2026-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busop', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
    ]
