# Generated by Django 5.2.10 on 2026-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busop', '0004_remove_bus_route_schedule_price_and_more'),
        ('busop', '0004_schedule_price_alter_seat_unique_together'),
    ]

    operations = [
    ]
