# Generated by Django 5.2.10 on 2026-02-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_booking_status_payment_payment_status_transaction'),
        ('user', '0003_booking_status_transaction'),
    ]

    operations = [
    ]
